config/routes.rb
Omr::Application.routes.draw do
  resources :pins

  devise_for :users
  root 'pins#index'
  get 'user_root' => 'pins#index', as: :user_root
  get 'about' => 'pages#about'

end

app/models/pin.rb
class Pin < ActiveRecord::Base

has_attached_file :image, styles: { medium: "320x500>" }


validates :description, presence: true
validates :user_id, presence: true
validates_attachment :image, presence: true,
                                  content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']},
                                  size: { less_than: 5.megabytes }

belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


has_many :pins


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   before_filter :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc")
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.new
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])

    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-error", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <small>
      <!-- <a href="http://onemothrails.com">One Month Rails</a> -->
      <%= link_to("One Month Rails", "http://onemothrails.com") %>
      by Team 31
    </small>
  </div>

app/views/layouts/_formEmailPassword.html.erb
<!-- name and email fields -->

        <div class="form-group">
            <label class="sr-only" for="exampleInputEmail2">Email address</label>
            <%= f.label :name %><br />
            <%= f.text_field :name, class: "form-control", autofocus: true, placeholder: "username"%><br>
            <%= f.label :email %><br />
            <%= f.email_field :email, type: "email", class: "form-control", id: "exampleInputEmail2", placeholder: "email@domain.com" %>
        </div>

<!-- password and password confirm fields -->

        <div class="form-group">
            <label class="sr-only" for="exampleInputPassword2">Password</label>
            <%= f.label :password %>
            <%= f.password_field :password, type: "password", class: "form-control", id: "exampleInputPassword2", placeholder: "password" %><br>
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, type: "password", class: "form-control", id: "exampleInputPassword2", placeholder: "confirm password"  %>
        </div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <!-- <a class="navbar-brand" href="#">One Month Rails</a> -->
    <%= link_to "One Month Rails", root_path, class: "navbar-brand" %>

  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to("Home", root_path) %></li>
      <li><%= link_to "About", about_path %></li>
      <!-- <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li><a href="#">Separated link</a></li>
          <li class="divider"></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li> -->
    </ul>
    <ul class="nav navbar-nav pull-right">
      <% if user_signed_in? %>
        <li><%= link_to("Add Pin", new_pin_path ) %></li>

        <li><%= link_to("Edit Profile", edit_user_registration_path ) %></li>
        <li><%= link_to("Logout", destroy_user_session_path, method: :delete ) %></li>
      <% else %>
        <li><%= link_to("Login", new_user_session_path) %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One Month Rails</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%=render 'layouts/header' %>
    <div class="container">
      <%= flash_messages %>

      <%= yield %>
    </div>
    <div class="container">
      <%=render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/_home.html.erb
<% unless user_signed_in? %>
<div class="jumbotron">
  <h1>Welcome to One Month Rails!</h1>
  <p>
        You've found the home page for the
        <!-- <a href="http://onemothrails.com">One Month Rails</a> -->
        <%= link_to("One Month Rails", "http://onemonthrails.com") %>
        application.
  </p>
  <p>
        <!-- <a href="#">Sign Up Now!</a> -->
        <%= link_to("Sign Up Now!", new_user_registration_path, class: "btn btn-success btn-lg" )%>
  </p>
</div>
<% end %>

app/views/pages/about.html.erb
<h1>About</h1><br>

<p>
      <%= link_to("One Month Rails", "http://onemonthrails.com")%>
      is a project to teach
      <%=link_to("Ruby on Rails", "http://rubyonrails.org") %>
      in one month. This is the sample application.
</p><br><br>

<p class="blockquote">
Team 31s Imagesharer without reinventing the wheel!
</p>

app/views/pins/_form.html.erb
<div class="row">
  <div class="col-md-6  col-md-offset-3">
      <div class="well well-md">

    <%= simple_form_for(@pin) do |f| %>
      <%= f.error_notification %>
      <%= f.full_error :image_file_size, class: "alert alert-error" %>
      <%= f.full_error :image_content_type, class: "alert alert-error" %>

<div class="form-group">
        <%= f.input :image, label: "Upload and image", class: "form-control" %><br>
        <%= f.text_field :description, as: :text, class: "form-control", placeholder: "Image description..."%>
</div>

      <div class="form-actions">
        <%= f.button :submit, class: "btn btn-default" %>
      </div>
    <% end %>
</div>
</div>
</div>

app/views/pins/_pin.html.erb
<div class="box">
  <%= link_to image_tag(pin.image.url(:medium), :class => "img-rounded img-responsive"), pin %>
  <p class="description">
    <%= pin.description %>
  </p>
  <p>
    <strong>
      Posted by <%= pin.user.name %>
    </strong>
  </p>

  <% if current_user == pin.user %>
  <p>
    <%= link_to 'Edit', edit_pin_path(pin) %>
    <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
  <% end %>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>

<div id="pins">
  <%= render @pins %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>


<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 ">

<div class="box box2">
          <%= image_tag(@pin.image(:medium), :class => "img-rounded img-responsive" )%>

      <p class="description">
       <%= @pin.description %>
      </p>
      <p>
        <strong>
          Posted by <%= @pin.user.name %>
        </strong>
      </p>
      <% if current_user == @pin.user %>
        <%= link_to 'Edit', edit_pin_path(@pin) %> |
      <% end %>
      <%= link_to 'Back', pins_path %>
  </div>
</div>

</div>